development:
  stripe_publishable_key: 'pk_test_51MayCmSB8N6aWrdgI10NYGAiArdhVbPksPq8Rv6NeEvvwGHNjPNVaJSnqa1OigJ4vD6P9CZYkxKeyRMEiyhEVzVJ00wnFmD811'
  stripe_secret_key: 'sk_test_51MayCmSB8N6aWrdgizvoo1E3w8NmKw1sclaQfIb5KaqVdnfbDkpvKs6lNNIP4VjRYkVlJ6z2hejy9ftfGYHtb8fV00sr1gUFeX'
  gocardless_access_token: 'sandbox_EBcv7YDdAFYWpVqA-JqSyZiUdkfSV5ENNAgz_H9p'

test:
  stripe_publishable_key: 'Your-stripe_publishable_key'
  stripe_secret_key: 'Your-stripe_secret_key'
  gocardless_access_token: 'Your-gocardless_access_token'

production:
  stripe_publishable_key: 'pk_test_51MayCmSB8N6aWrdgI10NYGAiArdhVbPksPq8Rv6NeEvvwGHNjPNVaJSnqa1OigJ4vD6P9CZYkxKeyRMEiyhEVzVJ00wnFmD811'
  stripe_secret_key: 'sk_test_51MayCmSB8N6aWrdgizvoo1E3w8NmKw1sclaQfIb5KaqVdnfbDkpvKs6lNNIP4VjRYkVlJ6z2hejy9ftfGYHtb8fV00sr1gUFeX'
  gocardless_access_token: 'live_ASBPEHKZFkARM_PdTfoEhC-3VQr50MCvaKdWtAiJ'
